### PR TITLE
SimpleCov Setup

### PR DESCRIPTION
**Pull request by EsamAl-Dabagh**
- SimpleCov and SimpleCov added to the Gemfile. 
- Coverage results are shown in the terminal after tests have run. 
- Current coverage stands at 54.84%

### CODE REVIEW

**Comment by LazySamir** [comment]
I'm unfamiliar with CI. Should we be having them pass before merging?

**Comment by EsamAl-Dabagh** [comment]
Travis is now passing. The issue was with where simplecov was inputted on the Gemfile. It needs to be in `group :development, :test`.

**Comment by LondonJim** [comment]
Recommend a squash and merge because of all the back and forth changes to narrow down the problem as to why travis was failing the pull request.

**Comment by LazySamir** [comment]
Approvals make sense.

**Pull request merged**
